### ISSUE TITLE
Tutorial 03 - Words Scraping: Comments

### ISSUE THREAD

**Issue by lakimenon** [lisc-tools/lisc#13]
"Words" Section:
- [x] Typo: First sentence incomplete

"Function Approach: scrape_words" section:
- [x] Add explanation of parameters (maybe as a comment) for scrape_words function
- [x] Include outputs for dat, d1
- [x] "Each data object...papers" : could be rephrased/elaborated to be clearer, maybe give examples for what exactly the "data" is
 - [x] "Print out some data": Might be useful to include a short note about what different information can be printed

"Object Approach: Words" Section:
- [x] Include words.results output
- [x] Add code for printing out information, such as in function approach part
- [x] "demonstrated above" --> "demonstrated in Tutorial 01"

"Metadata" Section:
- [x] Include words.meta_dat output
- [x] Typo: "scrape It" --> "scrape. It"
- [x] Specify that the Requester object is saved as 'req'
- [x] Can the 'en_time' attribute name be changed to 'end_time'? That might be more intuitive
- [x] Can seconds be included in the time? Minutes only might not be informative for smaller searches.

**Comment by TomDonoghue** [comment]
Thanks, @lakimenon for the very useful comments! I've folded these into the new tutorial structure!
