### ISSUE TITLE
Tutorial 01 - Counts Searching: Comments

### ISSUE THREAD

**Issue by lakimenon** [lisc-tools/lisc#14]
"Counts" Section:
- [x] Two "Counts" section headings. I think the first one is probably not necessary
- [x] Typo: "Specifically, it search" --> "Specifically, it searches"
- [x] Typo: "papers where found" --> "papers were found"
- [x] Explain the numbers for percent of paper overlap
- [x] Typo: "Print out many" --> "Print out how many"
- [x] Print out some of the variables such as dat_numbers and dat_percent for co-occurrence between two sets

"Count Object" section:
- [x] May be useful to include a short note explaining when/why it might be useful to use object method over function method
- [x] May look better if spacing between words in function outputs was reduced
- [x] Short explanation of what "highest association" means may be useful. Could also be more intuitive if a list with more than two terms was used

"Co-occurrence data - different word lists" section:
- [x] May look neater if section header was larger
- [x] Explicitly state (before code) that two separate lists are being used, and co-occurrence of terms between the two lists is being checked
- [x] Output template may be better if changed from "For the (term)" to "For (term)"

"Synonyms and Exclusion Words" section:
- [x] Typo: "For example, a using" --> "For example, using"
- [x] Weird quotations and spacing for "gene" OR "genetic" NOT "protein"
- [x] Point out that exclusion words correspond to the respective search terms, i.e. that "protein" is the exclusion term for gene/genetic and "subcortical" is the exclusion term for cortex/cortical
- [x] Include output for counts.terms['A'].labels
- [x] In the final note, point out that using the scrape_counts function is an alternative to using the Counts object

**Comment by TomDonoghue** [comment]
Thanks, @lakimenon for the very useful comments! I've folded these into the new tutorial structure!
