### ISSUE TITLE
typo in tutorial 00

### ISSUE THREAD

**Issue by koudyk** [lisc-tools/lisc#63]
Hello! Thanks for making this great package!

I noticed an inconsistency in these lines of the Overview tutorial:

```
147 # For example, the following set of search term components:
148 #
149 # - search terms ['brain', 'cortex']
150 # - inclusion words ['biology', 'biochemistry']
151 # - exclusion words ['body', 'corporeal']
152 #
153 # All combine to give the search term of:
154 #
155 # - `'("gene"OR"genetic)AND("biology"OR"biochemistry")NOT("body"OR"corporeal)'`
```

In order for the components to actually combine to the search term, I assume that either 
- line 149 should be `search terms ['gene', 'genetic']`, or
- line 155 should be `'("brain"OR"cortex)AND("biology"OR"biochemistry")NOT("body"OR"corporeal)'`

I thought probably the latter was correct, since 'gene' and 'genetic' hadn't been mentioned yet in the examples. 

Cheers

**Comment by TomDonoghue** [comment]
Thanks for bringing this up and fixing it in #64!
