### ISSUE TITLE
Collection content are literatures' full text, abstracts or the titles only?

### ISSUE THREAD

**Issue by suncyd** [lisc-tools/lisc#75]
Hello! Thank you so much for providing this useful tool and I would like to know the collection content are literatures' full text, abstracts or the titles only.

**Comment by TomDonoghue** [comment]
Hey @suncyd - the current implementation collects titles and abstract text. Full text could be extended from the tool, but is not currently implemented. 

Please see the [Documentation Site](https://lisc-tools.github.io/lisc/) and/or the [paper](https://joss.theoj.org/papers/10.21105/joss.01674) for further description of the module.

**Comment by suncyd** [comment]
Hello!
Thank you so much for your reply.
Best,
yuedi


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lisc-tools/lisc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月7日(星期天) 凌晨0:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lisc-tools/lisc] Collection content are literatures' full text, abstracts or the titles only? (Issue #75)





 
Hey @suncyd - the current implementation collects titles and abstract text. Full text could be extended from the tool, but is not currently implemented.
 
Please see the Documentation Site and/or the paper for further description of the module.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
