### ISSUE TITLE
Multiple terms collect question

### ISSUE THREAD

**Issue by skytguuu** [lisc-tools/lisc#76]
Hi,

Thanks for your developed tool "lisc". However, I am curious about the collection words with multiple terms. I have two lists of terms (terms_A and terms_B) and I want to use 'collect_words' to query the title and abstract of pubmed. However, I don't know how to use the co-occurance of these terms? 

BTW, I noticed the parameter of 'collect_words' had inclusion and exclusion:(collect_words(terms, inclusions=None, exclusions=None)), but I don't know how to use the inclusion, could you give me a example?

Thanks!

**Comment by TomDonoghue** [comment]
Please see the [documentation](https://lisc-tools.github.io/lisc/), and in particular the [tutorials](https://lisc-tools.github.io/lisc/auto_tutorials/index.html) for guidance on how to use the module. Collecting co-occurence is done with `collect_counts`, and how to use search terms is covered in the tutorials. 

Opening issues is to used for bug reports and clarifications of anything unclear from the documentation - but you should start by engaging with the available materials.

**Comment by skytguuu** [comment]
Hi,

Thanks for your promptly reply. I have followed the tutorials and indeed, the collect_counts have terms_a and terms_b, but is it still used for collect_words? I am a newer for python and I have tried several times, but it failed. Could you give me a hand?

I am appreciated for your help!
Thanks!

**Comment by TomDonoghue** [comment]
There is only one set of terms for "words" collection, so there is no 'A' and 'B'. The 'A' and 'B' is to collect co-occurences between two sets of terms. When collecting words data, it collects the papers returned by a single set of search terms.

**Comment by skytguuu** [comment]
Got it. Thanks for your help!


Many thanks!



发自我的iPhone


------------------ Original ------------------
From: Tom ***@***.***&gt;
Date: Tue,Nov 9,2021 0:07 AM
To: lisc-tools/lisc ***@***.***&gt;
Cc: skytguuu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lisc-tools/lisc] Multiple terms collect question (Issue #76)





 
There is only one set of terms for "words" collection, so there is no 'A' and 'B'. The 'A' and 'B' is to collect co-occurences between two sets of terms. When collecting words data, it collects the papers returned by a single set of search terms.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
