### ISSUE TITLE
co-occurence search within the pre-filtered data in Articles

### ISSUE THREAD

**Issue by guiomar** [lisc-tools/lisc#79]
Hi @TomDonoghue !

As always suped thankful for your very useful tools :)

I was wondering if you could do a co-occurence search, within the pre-filtered data in Articles. Or you would have to manage this throush the inclusion terms?

In this case for example:

Terms = ['word1','word2','word3'] --> Articles

TermsA = ['X']
InclusionA = ['x1','x2', Terms]

TermsB = ['Y']
InclusionA = ['y1','y2', Terms]

Terms: will look for 
'word1' OR 'word2' OR 'word3'
Whereas TermsA with InclusionA: will look for 
'X' AND ('x1' OR 'x2' **OR** ('word1' OR 'word3' OR 'word3'))
Or instead will it look for: 
'X' AND (('x1' OR 'x2') **AND**('word1' OR 'word3' OR 'word3'))
How it should be done to obain the latter case?

Thanks a lot!

**Comment by TomDonoghue** [comment]
hey @guiomar - I'm assuming this is now outdated, so I'm going to close this now - but if there is anything else / more, please feel free to reopen it / follow up!

**Comment by guiomar** [comment]
Hi @TomDonoghue! Thanks a lot! Indeed we managed to get what we wanted. My apologies for not communicating it. Always running. Thanks for your useful suggestions, and for all the awesome tools and resources you develop and openly share :)
