### ISSUE TITLE
URL length limit reached when fetching many articles

### ISSUE THREAD

**Issue by hahaschool** [lisc-tools/lisc#84]
Hi there, lisc is awesome and we have used it for a while, but we recently encountered some issues when searching papers.

To reproduce, we could build a method called `find_papers(num: int)` first:

```
from lisc.objects.base import Base
from lisc import Words
import re
import urllib.request

def find_papers(num):
    terms = [['Pembrolizumab']]
    inclusions = [['Predict']]
    exclusions = [['TIDE']]
    base = Base()
    base.add_terms(terms)
    base.add_terms(inclusions, 'inclusions')
    base.add_terms(exclusions, 'exclusions')
    print(base.make_search_term(0))
    words = Words()
    words.add_terms(terms)
    words.add_terms(inclusions,'inclusions')
    words.add_terms(exclusions,'exclusions')
    words.run_collection(retmax=num)
    # return a list of PubMed ID.
    pmid = words.results[0].ids
    return pmid

```

We call `find_papers(100)` and it's working fine, but we want to retrieve all papers so we increased `num` to 400+ and we found after passing a number we will suddenly not be able to retrieve anything. After reading the code we found this should be caused by the URL length limit. We have prepared a fix and we hope this can resolve this issue: https://github.com/lisc-tools/lisc/pull/85 .

Thank you.

Adam

**Comment by TomDonoghue** [comment]
Addressed in #85 - closing here

For anyone finding this issue - there is a fix in #85, but also this issue should be addressed by using history (`usehistory=True`)
